/**
 *
 * Copyright 2018-present rn_nongye
 *
 */

export const DAILY_REPORT_LIST = 'DAILY_REPORT_LIST';
export const MORE_DAILY_REPORT = 'MORE_DAILY_REPORT';
export const DAILY_REPORT_CURRENT = 'DAILY_REPORT_CURRENT';
export const UPDATE_DAILY_REPORT_LIST_TOTAL = 'UPDATE_DAILY_REPORT_LIST_TOTAL';
export const CREATE_DAILY_REPORT = 'CREATE_DAILY_REPORT';
export const EDIT_DAILY_REPORT = 'EDIT_DAILY_REPORT';
export const LIST_DATE_CURRENT = 'LIST_DATE_CURRENT';
export const LIST_PAGE_NO = 'LIST_PAGE_NO';
export const DAILY_REPORT_IS_MODIFY = 'DAILY_REPORT_IS_MODIFY';