export const GET_ALL_PROJECTS_GROUPS = 'GET_ALL_PROJECTS_GROUPS';
export const GET_ALL_PROJECTS_GROUPS_DONE = 'GET_ALL_PROJECTS_GROUPS_DONE';
export const GET_ALL_PROJECTS_GROUPS_ERROR = 'GET_ALL_PROJECTS_GROUPS_ERROR';

export const GET_WORKER_PROJECTS_GROUPS = 'GET_WORKER_PROJECTS_GROUPS';
export const GET_WORKER_PROJECTS_GROUPS_DONE = 'GET_WORKER_PROJECTS_GROUPS_DONE';
export const GET_WORKER_PROJECTS_GROUPS_ERROR = 'GET_WORKER_PROJECTS_GROUPS_ERROR';

export const GET_PROJECTS_BY_GROUP = 'GET_PROJECTS_BY_GROUP';
export const GET_PROJECTS_BY_GROUP_DONE = 'GET_PROJECTS_BY_GROUP_DONE';
export const GET_PROJECTS_BY_GROUP_ERROR = 'GET_PROJECTS_BY_GROUP_ERROR';

export const GET_ONLY_ONE_GROUP_PROJECTS = 'GET_ONLY_ONE_GROUP_PROJECTS';

export const SELECT_GROUP = 'SELECT_GROUP';
export const COPY_PROJECTS_FROM_ONLY_ONE_GROUP = 'COPY_PROJECTS_FROM_ONLY_ONE_GROUP';
export const RESET_SELECTED = 'RESET_SELECTED';

export const GET_PROJECTS_LIST_DATA = 'GET_PROJECTS_LIST_DATA';
export const GET_EVALUATION_TYPE_DATA = 'GET_EVALUATION_TYPE_DATA';
