export const USER_PHONE_REGISTERED = 'USER_PHONE_REGISTERED';
export const USER_PHONE_REGISTERED_DONE = 'USER_PHONE_REGISTERED_DONE';
export const USER_PHONE_REGISTERED_ERROR = 'USER_PHONE_REGISTERED_ERROR';

export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_SIGNIN_DONE = 'USER_SIGNIN_DONE';
export const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR';

export const USER_SIGNOUT = 'USER_SIGNOUT';

export const USER_LOADING = 'USER_LOADING';

export const USER_WORK_RIGHTS = 'USER_WORK_RIGHTS';
export const USER_MEMBER_RIGHTS = 'USER_MEMBER_RIGHTS';
