export const MONITOR_FETCH = 'MONITOR_FETCH'
export const MONITOR_FETCH_DONE = 'MONITOR_FETCH_DONE'
export const MONITOR_FETCH_ERROR = 'MONITOR_FETCH_ERROR'

export const MONITOR_LOADING = 'MONITOR_LOADING'
